import { AnimatePresence, motion } from 'framer-motion'
import { X } from 'lucide-react'
import { useForm } from 'react-hook-form'
import type { Profile } from '@/entities/hydration/model/types'
import { useTranslation } from '@/shared/lib/i18n'

interface Props { open: boolean; profile: Profile; onClose: () => void; onSave: (profile: Partial<Profile>) => void }
type FormValues = Pick<Profile, 'name' | 'age' | 'gender' | 'height' | 'weight' | 'activity' | 'workoutMinutes'>

export function EditProfileSheet({ open, profile, onClose, onSave }: Props) {
  const { t } = useTranslation()
  const { register, handleSubmit, formState: { errors, isValid } } = useForm<FormValues>({ values: profile, mode: 'onChange' })
  const submit = (values: FormValues) => { onSave(values); onClose() }
  return <AnimatePresence>{open && <><motion.button className="sheet-scrim" aria-label={t('close')} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}/><motion.section className="bottom-sheet profile-editor" role="dialog" aria-modal="true" initial={{ y: '105%' }} animate={{ y: 0 }} exit={{ y: '105%' }} transition={{ type: 'spring', stiffness: 320, damping: 31 }}><div className="sheet-handle"/><div className="sheet-heading"><div><p className="eyebrow">{t('personalData')}</p><h2>{t('editProfile')}</h2></div><button className="icon-button" onClick={onClose} aria-label={t('close')}><X size={20}/></button></div><form onSubmit={handleSubmit(submit)} className="profile-form"><label className="form-field wide"><span>{t('name')}</span><input {...register('name', { required: t('enterName'), minLength: 2 })}/><small>{errors.name?.message}</small></label><label className="form-field"><span>{t('age')}</span><input {...register('age', { valueAsNumber: true, min: 12, max: 120 })} inputMode="numeric"/><small>{errors.age ? '12–120' : ''}</small></label><label className="form-field"><span>{t('gender')}</span><select {...register('gender')}><option value="male">{t('male')}</option><option value="female">{t('female')}</option><option value="other">{t('other')}</option></select></label><label className="form-field"><span>{t('height')}, cm</span><input {...register('height', { valueAsNumber: true, min: 100, max: 250 })} inputMode="numeric"/><small>{errors.height ? '100–250 cm' : ''}</small></label><label className="form-field"><span>{t('weight')}, kg</span><input {...register('weight', { valueAsNumber: true, min: 25, max: 350 })} inputMode="decimal"/><small>{errors.weight ? '25–350 kg' : ''}</small></label><label className="form-field wide"><span>{t('activityLevel')}</span><select {...register('activity')}><option value="low">{t('low')}</option><option value="moderate">{t('moderate')}</option><option value="high">{t('high')}</option></select></label><label className="form-field wide"><span>{t('workoutMinutes')}</span><input {...register('workoutMinutes', { valueAsNumber: true, min: 0, max: 180 })} inputMode="numeric" placeholder="0"/><small>{errors.workoutMinutes ? '0–180 min' : ''}</small></label><button className="primary-action" type="submit" disabled={!isValid}>{t('saveChanges')}</button></form></motion.section></>}</AnimatePresence>
}
